language: dart

jobs:
  include:
    - stage: unit_test
      env: All unit tests
      dart_task:
      - test

stages:
  - unit_test

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pub-cache