name: dnb
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  meta: ^1.1.6
  http: ^0.12.0

  sigv4:
    git: https://github.com/arnemolland/sigv4.git