name: dnb
description: A Dart client library for interacting with DNB's open APIs.
version: 0.0.1
author: Arne Molland <arnolaim@gmail.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  meta: ^1.1.6
  http: ^0.12.0
  sigv4:
    git: https://github.com/arnemolland/sigv4.git

dev_dependencies:
  test: ^1.5.3
  dotenv: ^1.0.0